### ISSUE TITLE
Unfriendly message when login fails

### ISSUE THREAD

**Issue by fzoufaly** [MobilizeNet/BlackDiamondStudio#10]
When you try to login using AD and the user does not exist in the directory the error that is generated has not been "trapped" and it is the default unfriendly errror.

I would expect the error to be curated by us and to point to some web page where the user can contact Mobilize, get support, etc...
![image](https://user-images.githubusercontent.com/62109415/152617070-93b9e9df-6029-4e85-b74a-a44bdc9648c3.png)

**Comment by lcuello03** [comment]
Hi,

A new Bug report have been generated and can be tracked with Id #512770.

Thanks for the report!

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
