### ISSUE TITLE
[Data Loss][Scenario #1] No output code nor reports was found in the IDE after the migration

### ISSUE THREAD

**Issue by klunmobilize** [MobilizeNet/BlackDiamondStudio#11]
Description:
No output code nor reports was found in the IDE after the migration

Steps to reproduce:
1. Create new project
2. New migration project
3. Enter project name: Hello_Jorge
4. Press TAB , wait until the button of **Open in IDE** is available
5. Click Open in IDE
6. Add a Hello.sql file in the opened IDE, write something there
7. Go back to the Migration Pane
8. Fill all information of Connect Target Database
9. Migrate a Teradata code, and start migrating
10. Wait until it is finished
11. Click 'Back'
12. Scroll up to the top
13. Click **Open in IDE** 
14. You'll see that there is no output code

**Comment by AlonsoMontero** [comment]
Thanks for the report. Two questions:

1. Just to confirm: did you commit the **Hello.sql** and pushed that commit?
2. If you pull the changes from your branch, does the output appear?

**Comment by klunmobilize** [comment]
Nice, that is the reason. Maybe this is something that you can add into the documentation to clafiry this situation

**Comment by AlonsoMontero** [comment]
I agree with you, we will review how to make this flow more user-friendly.

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
