### ISSUE TITLE
Main page of BDS does not provide any help for a new user

### ISSUE THREAD

**Issue by fzoufaly** [MobilizeNet/BlackDiamondStudio#13]
the main page is just a login.  
I would suggest to have a description of the product, how to get a user, where to get feedback, etc...
I mean, some product explanation on the main page.

**Comment by kbejarano** [comment]
Hi @fzoufaly! Our UX Team has already design a tutorial for new users, this will be implemented according to the priorities for next releases, thank you for the suggestion!

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
