### ISSUE TITLE
Confusing Message and header

### ISSUE THREAD

**Issue by fzoufaly** [MobilizeNet/BlackDiamondStudio#14]
I selected the project option to create from the database.
When i start to insert the parameters it says: 

"Target Database" is it really a Target database in this case?  Should we use a different word? In this case it is both source and target....  
"Snowflake Account" ???  wouldn't it be better?

We are referring to Snowflake as a "database" this is actually forbidden by our partner guidelines.  Snowflake is a "Data Platform"  Instead of saying "Connect to your Snowflake Database" we should say "Connect to your Snowflake Account" We should review this nomenclature problem also in all the tips.

Let's just use "Snowflake Account" "Disconnect Snowflake" ....

![image](https://user-images.githubusercontent.com/62109415/152619152-259fbfa8-6aaf-40c0-a7be-7b3c31763c9e.png)

**Comment by lcuello03** [comment]
Hi,
A new Bug report has been generated. It can be tracked using the report: Bug # [513320](https://collaboration.artinsoft.com/tfs/Product/Bifrost/_workitems/edit/513320)

Thanks for the report!
