### ISSUE TITLE
Click on user icon on IDE and get a "Loading message" nothing happens

### ISSUE THREAD

**Issue by fzoufaly** [MobilizeNet/BlackDiamondStudio#17]
I clicked on the "user" icon on the left side of the IDE.  It says "loading..." but it does not do anything.  if you click on it again, the message disappears.

Why?

**Comment by lcuello03** [comment]
Hello, we are already tracking this issue. Thanks for reporting it!
We are tracking it with bug #[491131](https://collaboration.artinsoft.com/tfs/Product/Bifrost/_workitems/edit/491131).

**Comment by devops-bds** [comment]
This issue is duplicated. Please refer to [Issue](https://github.com/MobilizeNet/BlackDiamondStudio/issues/4).
