### ISSUE TITLE
References to Bifrost in Logger

### ISSUE THREAD

**Issue by freddycra** [MobilizeNet/BlackDiamondStudio#20]
**Describe the issue**
Reference to bifrost in logger.

**To Reproduce**
1. Open a project.
2. Click output (ctrl + shift + u)
3. In the dropdown select **Log (Remote Extension Host)**
4. Use searcher (ctrl + f) and search _bifrost_ there are several occurrences of a path that contains home/bifrost/... (see the screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/33108676/152622802-646f90aa-2673-4f53-8c76-c754a4209e4d.png)

**WebBrowser (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version V1.35.100

**Comment by craguilar-mobilize** [comment]
Hi , thank you for your comments, we have just created a bug #[512793](https://collaboration.artinsoft.com/tfs/Product/Bifrost/_workitems/edit/512793) to fix this, we hope to fix it as soon as possible.

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
