### ISSUE TITLE
should access to the "Terminal" be allowed?

### ISSUE THREAD

**Issue by fzoufaly** [MobilizeNet/BlackDiamondStudio#21]
You can open a terminal that allows you to see all the files in the workspace. (see attached screenshot).

Should this be allowed?  is there a use for the terminal to be available?

BTW, the notebook is called "bifrost"
![image](https://user-images.githubusercontent.com/62109415/152622887-babc02f3-b178-417a-93f7-69eeae3a4f1b.png)

**Comment by craguilar-mobilize** [comment]
Hi, thanks for your feedback, we already have a bug #[512793](https://collaboration.artinsoft.com/tfs/Product/Bifrost/_workitems/edit/512793) reported to fix the problem of the bifrost reference in the terminal, regarding the access in the terminal that is the default behavior now, but we will validate which permissions and access should be restricted.

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
