### ISSUE TITLE
Extract Source Code from Snowflake hangs forever

### ISSUE THREAD

**Issue by galahad-cr** [MobilizeNet/BlackDiamondStudio#22]
In the Projects configuration and after successfully configuring the "Project Name" and "Connect Database" steps, the "Extract Source Code from Snowflake" step hangs forever (currently still running after 12+ hours ). I can't use the new Project, in any regard, and I can't stop nor cancel the step anyhow.

To Reproduce
1. Go to 'Projects'
2. Click on '+' sign to add a new project
3. Configure the Project Name
4. Configure the Connect Target Database
5. At this point Extract Source Code from Snowflake will hang forever.

Expected behavior
As a User, my recently configured Project should be available to use. Also, the Extract Source Code from Snowflake step should fail after a reasonable amount of time, or at least show an expected time.

Screenshots

![image](https://user-images.githubusercontent.com/56230755/152657124-ee4c69f1-d7d4-4bfc-a4a3-47ae86d81801.png)

![Snowflake DW Project - Finishing project configuration](https://user-images.githubusercontent.com/56230755/152657055-2db6f379-be78-4409-947e-ecfbff8268ee.png)

![image](https://user-images.githubusercontent.com/56230755/152657079-17fead4b-6f78-46b0-9d2f-091e4d785deb.png)

Web Browser 
 - OS: Windows 10 (64 bit)
 - Browser Microsoft Edge / Mozilla Firefox
 - Version 98.0.1108.43 / 96.0.3 

Additional context
I'm a new user, never used Black Diamond before
I'm using a SYSADMIN log-in with full permissions over the objects in the

**Comment by lcuello03** [comment]
Hi,
A new bug report has been generated for this issue. It can be tracked using: Bug #[513425](https://collaboration.artinsoft.com/tfs/Product/Bifrost/_workitems/edit/513425)

Thanks for the report!

**Comment by rmelendez07** [comment]
Hi @galahad-cr, can you provide us the project's ID please, for tracking this issue better?
You can find it in the project's URL.

Thank you for your report.

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
