### ISSUE TITLE
Snowflake DW Project Connect Database step fails

### ISSUE THREAD

**Issue by galahad-cr** [MobilizeNet/BlackDiamondStudio#23]
In the Projects configuration and after configuring the "Project Name" and providing my connections information, I get a "Connection failed" message without any more information.

To Reproduce
1. Go to 'Projects'
2. Click on '+' sign to add a new project
3. Configure the Project Name
4. Configure the Connect Target Database

Expected behavior
The connection should succeed or present a more detailed error message to guide the User.

Screenshots

![image](https://user-images.githubusercontent.com/56230755/152657435-12cdddec-8a69-4b6a-9c03-25b7615748d9.png)

Web Browser
- OS: Windows 10 (64 bit)
- Browser Microsoft Edge / Mozilla Firefox
- Version 98.0.1108.43 / 96.0.3

**Additional context**
I'm a new user, never used Black Diamond before
I'm using a SYSADMIN log-in with full permissions over the objects in the
The Snowflake account is a free standard version

**Comment by lcuello03** [comment]
Hi, we already created a bug report for this issue.
And we are tracking it with Bug # [493807](https://collaboration.artinsoft.com/tfs/Product/Bifrost/_workitems/edit/493807).

Thanks for your report!

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
