### ISSUE TITLE
Show Password option disappear in "Connect Target Database"

### ISSUE THREAD

**Issue by freddycra** [MobilizeNet/BlackDiamondStudio#25]
**Describe the issue**
I can show the password just one time, then the show password option disappears forever.

**To Reproduce**
1. Open Projects dashboard https://bds.mobilize.net/
2. Click on + sign to add new project
3. Select Migration Project
4. Add Project name
5. Fill in all the data of the "Connect Target Database" form
![image](https://user-images.githubusercontent.com/33108676/152658267-6ad340f3-a937-4b89-8759-35ded427baf1.png)
6. Copy and paste any password 
7. The show password option is displayed 
![image](https://user-images.githubusercontent.com/33108676/152658415-bfebfa77-7256-4609-943e-1c1de23c44a4.png)
8. Click anywhere else outside the form
9. The show password option disappeared. Nor even modifying the password is displayed
![image](https://user-images.githubusercontent.com/33108676/152658493-13015371-738c-4a67-9bc2-9839a06bce77.png)

**Expected behavior**
The show password button should be displayed when typing a new password or after the password was modified.

**Screenshots**
screenshots in the steps to reproduce

**WebBrowser (please complete the following information):**
 - OS: Windows 10
 - Browser Tested in Microsoft Edge (98.0.1108.43)  and Brave (V1.35.100)

**Comment by freddycra** [comment]
[Update] I found some scenarios where the button to show the password was never displayed.

**Comment by lcuello03** [comment]
Hi,
A new report has been created, it can be tracked using: Bug #[513471](https://collaboration.artinsoft.com/tfs/Product/Bifrost/_workitems/edit/513471)

Thanks for your report!

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
