### ISSUE TITLE
Recover password email content is not accurate

### ISSUE THREAD

**Issue by freddycra** [MobilizeNet/BlackDiamondStudio#27]
**Describe the issue**
When recovering a password email is sent with a code to recover the password. But this email says: Thanks for verifying your falvarado@mobilize.net account!
I think the message should say something like: 
![image](https://user-images.githubusercontent.com/33108676/152659060-92dd2217-a877-4eca-b79c-3bb6dcc7e20c.png)

**To Reproduce**
1. Open private window
2. Go to site https://bds.mobilize.net/
3. Press the "sign in with email" button.
4. Press "Forgot your password?" link
![image](https://user-images.githubusercontent.com/33108676/152659211-8311bc69-5c50-4216-b51a-20946ebb6140.png)
5. Type the email
6. Press "Send verification code" button
7. Check the email

**Expected behavior**
Email should say something related to password recovery, not verification account message.

**Screenshots**
![image](https://user-images.githubusercontent.com/33108676/152659283-6949e207-21c3-46d5-9d18-ae9240261cc3.png)

**WebBrowser (please complete the following information):**
 - OS: Windows 10
 - Browser Brave 
 - Version V1.35.100

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
