### ISSUE TITLE
Reference to Bifrost in Account Verification and recover password emails

### ISSUE THREAD

**Issue by freddycra** [MobilizeNet/BlackDiamondStudio#28]
**Describe the issue**
Reference to Bifrost in Account Verification and recover password emails.

**To Reproduce**
1. Create new account and check the email

Another way:
1. Open private window
2. Go to site https://bds.mobilize.net/
3. Press the "sign in with email" button.
4. Press "Forgot your password?" link
5. Type the email
6. Press "Send verification code" button
7. Check the email

**Expected behavior**
It should say Blackdiamond

**Screenshots**
![image](https://user-images.githubusercontent.com/33108676/152659435-fcce003d-abdb-4717-a7f3-c2caefb0b7c2.png)

**WebBrowser (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version V1.35.100

**Comment by kbejarano** [comment]
Hi @freddycra! Thank you for reporting, we're tracking it with bug[ #513492](https://collaboration.artinsoft.com/tfs/Product/Bifrost/_workitems/edit/513492/)

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
