### ISSUE TITLE
Email verification mail poorly formatted

### ISSUE THREAD

**Issue by MobilizeNetBlog** [MobilizeNet/BlackDiamondStudio#30]
![account verification mail](https://user-images.githubusercontent.com/7683137/152662003-d05cfb76-c07a-4940-b777-5877385ba1ef.jpg)

Note the email that the user receives when they request a password reset is poorly formatted (see screen shot).

**Comment by AlonsoMontero** [comment]
Thank you for this feedback. We will be tracking this issue with Bug #513463.

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
