### ISSUE TITLE
Migration failed: where is log folder?

### ISSUE THREAD

**Issue by MobilizeNetBlog** [MobilizeNet/BlackDiamondStudio#32]
*
<img width="424" alt="Snag_55d1e8e" src="https://user-images.githubusercontent.com/7683137/152663901-5aecab94-a715-4c09-9b35-01597e279476.png">
Error message after failed BDS migration says "check the log folder for more details" but I have no clue where that folder might be. 

Expected: path or description of where log folder is created by default.

Also: Can I change paths for created files? What if I don't want my migration in the same folder as the source files?

**Comment by AlonsoMontero** [comment]
Thanks for the feedback. This issue is now being tracked with Bug #513476.
