### ISSUE TITLE
Favicon on IDE makes no sense

### ISSUE THREAD

**Issue by MobilizeNetBlog** [MobilizeNet/BlackDiamondStudio#36]
**Describe the issue**
The favicon in Chrome for the tab with BDS IDE makes no sense. Looks like a tiny dude in a wheelchair ramming a curly brace.

**To Reproduce**
Set Chrome to default browser
Open IDE from BDS after migration
See favicon

**Expected behavior**
Chrome favicon should look like BDS icon

**Screenshots**
<img width="364" alt="Snag_955492a" src="https://user-images.githubusercontent.com/7683137/152697528-f1079bf8-3bc9-46d5-85fd-bf3e5ebbee2e.png">

**WebBrowser (please complete the following information):**
 - OS: Win11
 - Browser Chrome
 - Version 97.0.4692.99 (Official Build) (64-bit)

**Additional context**

**Comment by lcuello03** [comment]
Hi,
This issue has been already fixed, and will be available for next releases.

Thanks for your report!

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
