### ISSUE TITLE
Identification of files in compare mode confusing or wrong

### ISSUE THREAD

**Issue by MobilizeNetBlog** [MobilizeNet/BlackDiamondStudio#39]
**Describe the issue**

**To Reproduce**
Use "Select for compare" and "compare to selected" on two versions (source and target) of the same file in the IDE. 

**Expected behavior**
Clear identification of which file is on the left and which is on the right. The heading now is confusing in that it seems to imply the target is on the left and the source is on the right (see annotations below). For example, in BeyondCompare, the context menu uses "Select Left Folder for Compare" which clearly sets the user expectation the folder will be on the left in the comparison view.

**Screenshots**
<img width="988" alt="Snag_96b3be1" src="https://user-images.githubusercontent.com/7683137/152698383-5916d4ff-0ffa-4259-91dd-5e94d5136e5d.png">

**WebBrowser (please complete the following information):**
 - OS: Win 11
 - BrowserChrome
 - Version 97.0.4692.99 (Official Build) (64-bit)

**Additional context**

**Comment by kbejarano** [comment]
Hello @MobilizeNetBlog! Thank you for reporting, we will track this with bug [#513520]([Bug 513520](https://collaboration.artinsoft.com/tfs/Product/Bifrost/_workitems/edit/513520): [Bifrost] Identification of files in compare mode confusing or wrong)

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
