### ISSUE TITLE
Vertical scrollbar is always visible on projects page

### ISSUE THREAD

**Issue by jmartinez894** [MobilizeNet/BlackDiamondStudio#40]
**Describe the issue**
The vertical scrollbar is always visible on projects page when is not required.

**To Reproduce**
1. Go to https://bds.mobilize.net/
2. Sign in with your credentials
3. The projects page is visualized

**Expected behavior**
The vertical scrollbar only should be visible when required.

**Screenshots**
![image](https://user-images.githubusercontent.com/39496208/152797847-67ca77ee-6815-4591-b90b-176646bd4c91.png)

**WebBrowser (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 93.0.4577.63

**Comment by kbejarano** [comment]
Hi @jmartinez894, thank you for reporting! We'll track this issue with the bug item [#513501](https://collaboration.artinsoft.com/tfs/Product/Bifrost/_workitems/edit/513501)

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
