### ISSUE TITLE
Cloud Session never expires

### ISSUE THREAD

**Issue by fzoufaly** [MobilizeNet/BlackDiamondStudio#41]
I left BDS open for 2 days without using it.  The cloud session never expired.
Does this mean that we are paying for the cloud cost during all the downtime?
Should there be some expiration ?  Something like if the session is not touched in 4 hours? then we auto log-out?  Isn't this a security issue as well?

**Comment by AlonsoMontero** [comment]
Hello, when you say you left BDS open, do you mean you left the portal open or the IDE open (or both)? 

In the case of the portal, it would not represent a cost, as far as I am aware. However, it could represent a security issue if you can use the same session after having left it open for 2 days. 

In the case of the IDE, I understand that it represents some cost, and could equally be a security issue.

**Comment by AlonsoMontero** [comment]
By the way, which browser (with its version) were you using?

**Comment by AlonsoMontero** [comment]
We will be tracking this issue with Bug #513526.

**Comment by fzoufaly** [comment]
Desktop App: 2.0.105

Conversion Core: 3.2.86.0

but  i believe the same problem also happened with the previous version.

**Comment by fzoufaly** [comment]
I am currently using EDGE.  

Microsoft Edge
Version 97.0.1072.76 (Official build) (64-bit)

**Comment by AlonsoMontero** [comment]
Thank you, we will be working on this issue.

**Comment by fzoufaly** [comment]
Both the IDE and the Portal stayed open for 2 days without any usage.

**Comment by AlonsoMontero** [comment]
Ok, understood.

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
