### ISSUE TITLE
Account menu item on BDS IDE only says "Loading"

### ISSUE THREAD

**Issue by MobilizeNetBlog** [MobilizeNet/BlackDiamondStudio#45]
**Describe the issue**
click on the Account icon on the left panel of the IDE. Says "Loading" and that's it. Just "loading". Nothing more. Nada mas. Nyet. Non. Nein mehr. Bupkus. Zilch. 

**To Reproduce**
See above

**Expected behavior**
Something? Not just "loading"

**Scre
<img width="430" alt="Snag_de6eaf2" src="https://user-images.githubusercontent.com/7683137/152830631-d69a5c59-e61f-4b17-819d-b154bcc43b41.png">
enshots**

**WebBrowser (please complete the following information):**
 - OS: Win 11
 - BrowserChrome
 - Version 97.0.4692.99 (Official Build) (64-bit)

**Additional context**

**Comment by lcuello03** [comment]
Hello, we are already tracking this issue. Thanks for reporting it!
We are tracking it with bug #491131.
