### ISSUE TITLE
Clicking Test icon generates unfathomable error: "Mocha: Error"

### ISSUE THREAD

**Issue by MobilizeNetBlog** [MobilizeNet/BlackDiamondStudio#47]
**Describe the issue**
Clicking the Erlenmeyer Flask icon (yeah, I studied chemistry) in the left panel of the IDE, the UI says Mocha: Testing. I have no idea what that's supposed to mean except something went wrong. 
 
**To Reproduce**
Connect to BDS Snowflake bug datawarehouse, 
Extract code
Open in IDE
Click test icon

**Expected behavior**
either: a proper testing UI would arise, or some more understandable and actionable error message would be shown. 

**Screenshots**
<img width="430" alt="Snag_dea0801" src="https://user-images.githubusercontent.com/7683137/152831189-df93f677-c646-4aba-900a-ffafbde97549.png">

**WebBrowser (please complete the following information):**

**Additional context**

**Comment by lcuello03** [comment]
Hi,
A new report has been generated for this issue. It can be tracked using: Bug #513518

Thanks for the report!

**Comment by devops-bds** [comment]
This issue is duplicated, Please refer to [this issue](https://github.com/MobilizeNet/BlackDiamondStudio/issues/16)
