### ISSUE TITLE
Compare does not work on Python extension

### ISSUE THREAD

**Issue by fzoufaly** [MobilizeNet/BlackDiamondStudio#49]
I tried to compare a converted BTEQ to Python  and i got an error that the "Source file could not be found".
(see attached screenshots).
I understand the file is quite different, but then, why do i have a compare option?  Or is there a compare type that works for this type of file?
![image](https://user-images.githubusercontent.com/62109415/152832786-cfee15eb-c393-49ac-a48d-2c47780decaf.png)

**Comment by AlonsoMontero** [comment]
We will be tracking this issue with Bug #513546.

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
