### ISSUE TITLE
Continue button in recovering password screen should be disabled

### ISSUE THREAD

**Issue by olmangarcia** [MobilizeNet/BlackDiamondStudio#52]
When recovering password there is a verification code validation, at that point before entering the verification button the "Continue" button is enable, you can click it and get an error.  Button should be disabled till verification code has been entered and verified.

![image](https://user-images.githubusercontent.com/4909156/152857871-86b52f3c-2d79-40f3-ba10-df3956c53412.png)

**Comment by rmelendez07** [comment]
Hi @olmangarcia, thanks for your feedback. We are handling it as a bug #513553.
