### ISSUE TITLE
error on "conversion un progress"

### ISSUE THREAD

**Issue by nhidalgoa** [MobilizeNet/BlackDiamondStudio#54]
after adding the .zip file, was 10+ minutes reading source code but never ends, was necessary a reload.

**To Reproduce**
Create new project
Conversion Project
Platform SQLServer
Start conversion

**Screenshots**
![image](https://user-images.githubusercontent.com/94459483/152869615-5c187fbb-e185-46e8-9c0d-588c11a1fa55.png)

**WebBrowser (please complete the following information):**
 - OS: [Windows]
 - Browser [EDGE]
 - Version [ 97.0.1072.76]

![Capture](https://user-images.githubusercontent.com/94459483/152869680-457cce54-64a0-46b7-b0bf-83bf48b98de3.PNG)

**Comment by lcuello03** [comment]
Hi,
We already are tracking this issue with report: Bug #513425

Thanks for your report.

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed
