### ISSUE TITLE
Licenses email when my first project is created are confuse

### ISSUE THREAD

**Issue by jmartinez894** [MobilizeNet/BlackDiamondStudio#55]
**Describe the issue**
When a first project is created in BlackDiamond some emails are sent to the register email when I sign up.  It seems confuse because any information is provided to let us know that the email will be send and is not useful inside the BlackDiamond website. Also the email template do not have any info that comes from BlackDiamond.

**To Reproduce**
1- Go to https://bds.mobilize.net/
2- Sign in with your credentials
3- Create your first project
4- Check your email for the licenses emails

**Screenshots**
![image](https://user-images.githubusercontent.com/39496208/152870453-dfc0d1d5-e350-4901-9049-5754d5585870.png)

**WebBrowser (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 93.0.4577.63

**Comment by AlonsoMontero** [comment]
Thanks for your feedback. We will remove this emails. We are tracking this issue with Bug #513531.

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
