### ISSUE TITLE
Unable to remove/add uploaded zip file for conversion

### ISSUE THREAD

**Issue by oherrera-mob** [MobilizeNet/BlackDiamondStudio#58]
**Describe the issue**
I upload a zip file with SQL files to convert

**To Reproduce**
1. Go to 'Convert Source Code'
2. Click on 'Choose Source Platform' and select 'SQL Server'
3. Upload zip file and wait until finish upload
4. There is no option to delete file

**Expected behavior**
An option to delete file and then upload it again.

**Screenshots**

![image](https://user-images.githubusercontent.com/94491407/152874265-3dd12946-8533-48a7-b9f6-d6b1375ae6a4.png)

**WebBrowser:**
OS: [Windows]
Browser [EDGE]
Version [97.0.1072.62]

**Comment by lcuello03** [comment]
Hi,
Currently this is the defined behavior for the migration process, but we will be working with our UI/UX team to generate a better user experience and validate the corresponding features that will be available for the next releases.

Thanks for your report!

**Comment by devops-bds** [comment]
This is the expected behavior for this process, uploaded files can be deleted from the repo or IDE.
