### ISSUE TITLE
bifrost word on url

### ISSUE THREAD

**Issue by nhidalgoa** [MobilizeNet/BlackDiamondStudio#60]
in the conversion page, the word bifrost is in url
![bifrost word url](https://user-images.githubusercontent.com/94459483/152883289-64445e93-b500-49de-b85c-1314e68f880a.PNG)

**Comment by AlonsoMontero** [comment]
Hello, this only happens on the staging environment. The link provided in the email* is the one that should be used.

*The email that was sent with instructions about how to participate in the Bug Bash.
