### ISSUE TITLE
bifrost word on output

### ISSUE THREAD

**Issue by nhidalgoa** [MobilizeNet/BlackDiamondStudio#61]
bifrost word on output after cancel the deploy

Right click on any file
BlackDiamond: Deply
Press Escape
![bifrost word on deploy](https://user-images.githubusercontent.com/94459483/152887365-5c07fff0-a863-4fb8-80f1-e078aa525332.PNG)

**Comment by AlonsoMontero** [comment]
Hello, thanks for the feedback. We are tracking this issue with Bug #512793. This is related to Issue #20 .

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
