### ISSUE TITLE
Snow Explorer: Migration Issues

### ISSUE THREAD

**Issue by alalvarado-m** [MobilizeNet/BlackDiamondStudio#62]
**Describe the issue**
Snow Explorer only displays "Migration Issues" on the panel, there are no issues and this seems confusing, 

**Expected behavior**
It is not clear if it should display the migration issues or  some kind of object explorer but not doing so because there are migration issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/84032740/152887000-237c53b8-523c-4914-9cc8-d7ad5b92daae.png)

**WebBrowser (please complete the following information):**
 - OS: Win 10 pro 
 - Chrome Version 97.0.4692.99

**Comment by craguilar-mobilize** [comment]
Hi, thanks for your feedback!, we will consider adding a more descriptive message for the user in the Snow Explorer in the next releases.

**Comment by orellabac** [comment]
I think snow explorer is a misleading name. Usually we would expect the snowexplorer to provide a mechanism to "explore the snowflake account"

Migration Issues or Issues Analyzer could be better

**Comment by devops-bds** [comment]
This issue has been solved and deployed.
