### ISSUE TITLE
bifrost word on terminal

### ISSUE THREAD

**Issue by nhidalgoa** [MobilizeNet/BlackDiamondStudio#63]
On the IDE, when open a terminal, shows bifrost word
right click on a file or folder
open in integrated terminal

![bifrost word terminal](https://user-images.githubusercontent.com/94459483/152888665-c8d735e4-38d2-4664-aeac-f471639fe0e1.PNG)

**Comment by AlonsoMontero** [comment]
Hello, thanks for your feedback. This is a duplicate of #20 .

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
