### ISSUE TITLE
Get all platforms licenses at once for Conversion Project

### ISSUE THREAD

**Issue by mfduartea** [MobilizeNet/BlackDiamondStudio#67]
**Describe the issue**
When I was trying to create a new conversion project, I selected SQL Server as the source platform. Immediately, I received the licenses for all the platforms at once through email. I don't think the company should "waste" licenses on that way. 

**Expected behavior**
After the code is converted, the user should receive an email with the corresponding source platform license.

**Screenshots**
![image](https://user-images.githubusercontent.com/92807850/152890555-7072ee8e-78f9-4ed7-af1a-61f0290e93cd.png)

**Comment by christiandcruz** [comment]
Hi, We are working on that! Thanks for you feedback.

**Comment by christiandcruz** [comment]
In search of improving this process, we are going to disable this sending of emails. Right now, we are handling this as Bug #513531

**Comment by jofallas** [comment]
Fixed

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.
