### ISSUE TITLE
Bug: Delete action not working with older projects

### ISSUE THREAD

**Issue by galahad-cr** [MobilizeNet/BlackDiamondStudio#69]
**Describe the issue**
When deleting an existing project, an error message box appears in the bottom-right corner. This message doesn't provide further information, and the project remains untouched in the BDS dashboard.

**To Reproduce**
1. Go to the projects dashboard (https://bds.mobilize.net/).
2. Hoover on an existing project.
3. Click the three dots (on the right-top corner).
4. Click the 'Delete' option.
5. Confirm your selection.

**Expected behavior**
The selected project's successfully deleted.
The error message box should provide additional information when clicked. 
Also, try to make this message more visible to the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/56230755/177605361-33ac913e-6072-49d7-8752-954ca9c2468a.png)
The numbers represent the steps I followed to reproduce the error.

**WebBrowser (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft EdgeVersion
 - Version 103.0.1264.44 (Official build) (64-bit)

**Additional context**
It only happened with older projects I created for an **earlier bug bash in February 2022**. 
Newly created projects don't behave like this.

**Comment by AlonsoM45** [comment]
Hello, we are currently tracking this bug with the ID 602261. Our team has already identified the issue and we will solve it as soon as possible. Thank you for reporting it!

**Comment by devops-bds** [comment]
This issue has been fixed and is already deployed.

**Comment by galahad-cr** [comment]
> Hello, we are currently tracking this bug with the ID 602261. Our team has already identified the issue and we will solve it as soon as possible. Thank you for reporting it!

Hey, Sorry for the late reply. Thanks for the follow up. Keep up the good work!
