### ISSUE TITLE
References to Bifrost in the documentation

### ISSUE THREAD

**Issue by freddycra** [MobilizeNet/BlackDiamondStudio#7]
**Describe the issue**
References to Bifrost in the Release notes documentation

**To Reproduce**
1. Go to https://docs.mobilize.net/bifrost-documentation-or-mobilize.net/blackdiamond-studio-documentation/release-notes

**Screenshots**
![image](https://user-images.githubusercontent.com/33108676/152615125-7dc715c5-ce2b-4d9c-8707-bbd04153c7b1.png)

**WebBrowser (please complete the following information):**
 - OS: Windows
 - Browser Brave
 - Version  V1.35.100

**Comment by freddycra** [comment]
**Describe the issue**
Another reference to Bifrost in the documentation

**To Reproduce**
Steps to reproduce the behavior:
1. Go to https://docs.mobilize.net/bifrost-documentation-or-mobilize.net/blackdiamond-studio-documentation/user-guide/ide/workspace#conversion-projects

**Screenshots**
![image](https://user-images.githubusercontent.com/33108676/152615471-048ba0b3-c5f3-4265-810f-ceb14c5c2ec6.png)

**Comment by craguilar-mobilize** [comment]
Hi, thanks for your feedback, we will make the necessary changes to the documentation to keep it as up to date as possible and to keep it as accurate as possible. The issue will be addressed asap.

**Comment by freddycra** [comment]
![image](https://user-images.githubusercontent.com/33108676/152621200-7b1c74bf-b668-4e13-bfbb-4005ad2e57cc.png)

This also looks incomplete!
